runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- appstats: on

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /admin
  static_files: static/admin.html
  upload: static/admin.html
  secure: always
  login: admin

- url: /static/js/admin.js
  static_files: static/js/admin.js
  upload: static/js/admin.js
  secure: always
  login: admin

- url: /favicon\.ico
  static_files: static/resources/favicon.ico
  upload: static/resources/favicon\.ico

- url: /notification
  script: notification.app
  secure: always
  login: admin

- url: /config(/.*)?
  script: notification.app
  secure: always
  login: admin

- url: /docs(/.*)?
  script: docs.app
  secure: always
  login: admin

- url: /(version|lead(/.*)?)
  script: landing.app

- url: /static
  static_dir: static

- url: /
  static_files: frontend/index.html
  upload: frontend/index.html

- url: /
  static_dir: frontend


libraries:
- name: webapp2
  version: latest
